# Generated by Django 4.2.1 on 2023-08-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('c', 'Chexol'), ('n', 'Nakidka'), ('p', 'Polik')], max_length=1)),
                ('title', models.CharField(max_length=256, verbose_name='Part name')),
                ('color_title', models.CharField(max_length=64, verbose_name='Color name')),
                ('hex', models.CharField(max_length=24, verbose_name='Color hex value')),
                ('photo', models.ImageField(upload_to='constructor/parts/', verbose_name='Photo of the part')),
            ],
            options={
                'verbose_name': 'Part',
                'verbose_name_plural': 'Parts',
            },
        ),
    ]
