# Generated by Django 4.2.1 on 2023-09-28 11:11

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('c', 'Chexol'), ('n', 'Nakidka'), ('p', 'Polik')], max_length=1)),
                ('title', models.CharField(max_length=256, verbose_name='Product model')),
                ('photo', models.ImageField(upload_to='constructor/models/', verbose_name='Default photo')),
            ],
            options={
                'verbose_name': 'Custom product model',
                'verbose_name_plural': 'Custom product models',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('c', 'Chexol'), ('n', 'Nakidka'), ('p', 'Polik')], max_length=1)),
                ('subcategory', models.CharField(choices=[('c', 'Central part'), ('b', 'Back part'), ('r', 'Rear part'), ('s', 'Stitch'), ('k', 'Kant')], max_length=1)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Part name')),
                ('photo', models.ImageField(upload_to='constructor/parts/', verbose_name='Photo of the part')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='store.color', verbose_name='Color of the part')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='store.buildingmaterial', verbose_name='Material')),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='constructor.customproductmodel', verbose_name='Product model')),
            ],
            options={
                'verbose_name': 'Part',
                'verbose_name_plural': 'Parts',
            },
        ),
        migrations.CreateModel(
            name='CustomProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('category', models.CharField(choices=[('c', 'Chexol'), ('n', 'Nakidka'), ('p', 'Polik')], max_length=1)),
                ('full_name', models.CharField(max_length=128, verbose_name='Full name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('photo', models.ImageField(upload_to='images/constructor/products/%Y/%m/', verbose_name='Constructed product photo')),
                ('remove_logo', models.BooleanField(default=False, verbose_name='Remove the logo?')),
                ('remove_podpyatnik', models.BooleanField(blank=True, default=False, null=True, verbose_name='Remove the podpyatnik')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active status')),
                ('car_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_products', to='store.carmodel', verbose_name='Car model')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_products', to='store.product', verbose_name='Product')),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='constructor.customproductmodel', verbose_name='Product model')),
            ],
            options={
                'verbose_name': 'Custom product',
                'verbose_name_plural': 'Custom products',
            },
        ),
    ]
