# Generated by Django 4.2.1 on 2023-08-26 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_store_is_official'),
        ('constructor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('c', 'Chexol'), ('n', 'Nakidka'), ('p', 'Polik')], max_length=1)),
                ('title', models.CharField(max_length=256, verbose_name='Product model')),
                ('photo', models.ImageField(upload_to='constructor/models/', verbose_name='Default photo')),
            ],
            options={
                'verbose_name': 'Custom product model',
                'verbose_name_plural': 'Custom product models',
            },
        ),
        migrations.RemoveField(
            model_name='part',
            name='color_title',
        ),
        migrations.RemoveField(
            model_name='part',
            name='hex',
        ),
        migrations.AddField(
            model_name='part',
            name='color',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='store.color', verbose_name='Color of the part'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='material',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='store.buildingmaterial', verbose_name='Material'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='subcategory',
            field=models.CharField(choices=[('c', 'Central part'), ('b', 'Back part'), ('r', 'Rear part'), ('s', 'Stitch'), ('k', 'Kant')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='part',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Part name'),
        ),
        migrations.CreateModel(
            name='CustomProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('category', models.CharField(choices=[('c', 'Chexol'), ('n', 'Nakidka'), ('p', 'Polik')], max_length=1)),
                ('remove_logo', models.BooleanField(default=False, verbose_name='Remove the logo?')),
                ('remove_podpyatnik', models.BooleanField(blank=True, default=False, null=True, verbose_name='Remove the podpyatnik')),
                ('back_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bp_products', to='constructor.part', verbose_name='Back part')),
                ('central_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cp_products', to='constructor.part', verbose_name='Central part')),
                ('kant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='k_products', to='constructor.part', verbose_name='Kant')),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='constructor.customproductmodel', verbose_name='Product model')),
                ('rear_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rp_products', to='constructor.part', verbose_name='Rear part')),
                ('stitch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='s_products', to='constructor.part', verbose_name='Stitch')),
            ],
            options={
                'verbose_name': 'Custom product',
                'verbose_name_plural': 'Custom products',
            },
        ),
        migrations.AddField(
            model_name='part',
            name='product_model',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='constructor.customproductmodel', verbose_name='Product model'),
            preserve_default=False,
        ),
    ]
