# Generated by Django 4.2.1 on 2023-10-04 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customproduct',
            name='product_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='constructor.customproductmodel', verbose_name='Product model'),
        ),
    ]
