# Generated by Django 4.2.1 on 2023-10-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0002_alter_customproduct_product_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customproduct',
            name='email',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Email'),
        ),
    ]
