# Generated by Django 4.2.1 on 2023-09-20 12:06

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_articul'),
        ('constructor', '0002_customproductmodel_remove_part_color_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customproduct',
            name='back_part',
        ),
        migrations.RemoveField(
            model_name='customproduct',
            name='central_part',
        ),
        migrations.RemoveField(
            model_name='customproduct',
            name='kant',
        ),
        migrations.RemoveField(
            model_name='customproduct',
            name='rear_part',
        ),
        migrations.RemoveField(
            model_name='customproduct',
            name='stitch',
        ),
        migrations.AddField(
            model_name='customproduct',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='customproduct',
            name='full_name',
            field=models.CharField(default='banzay', max_length=128, verbose_name='Full name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customproduct',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active status'),
        ),
        migrations.AddField(
            model_name='customproduct',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+998912958899', max_length=128, region=None, verbose_name='Phone number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customproduct',
            name='photo',
            field=models.ImageField(default=0, upload_to='images/constructor/products/%Y/%m/', verbose_name='Constructed product photo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_products', to='store.product', verbose_name='Product'),
        ),
    ]
