# Generated by Django 4.2.1 on 2023-09-28 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_store_iframe'),
        ('constructor', '0003_remove_customproduct_back_part_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customproduct',
            name='car_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_products', to='store.carmodel', verbose_name='Car model'),
        ),
    ]
