# Generated by Django 4.2.1 on 2023-08-18 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttype',
            name='title_en',
        ),
    ]
