# Generated by Django 4.2.1 on 2023-08-31 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_payment_method_order_is_canceled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='final_price',
        ),
    ]
