# Generated by Django 4.2.1 on 2023-09-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='cost',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cost'),
        ),
    ]
