# Generated by Django 4.2.1 on 2023-09-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderitem_articul'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='address',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Destination city'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Delivery date'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='level',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Floor number'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='region',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Region'),
        ),
    ]
