# Generated by Django 4.2.1 on 2023-10-03 12:07

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=128, null=True, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=128, null=True, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
            },
        ),
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Car brand',
                'verbose_name_plural': 'Car brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=128, null=True, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=128, null=True, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('hex_value', models.CharField(max_length=24, verbose_name='Hex value')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='UZ', verbose_name='Phone number')),
                ('is_official', models.BooleanField(default=True, verbose_name='Is official?')),
                ('region', models.CharField(max_length=128, verbose_name='Region')),
                ('district', models.CharField(max_length=128, verbose_name='City or district')),
                ('address', models.CharField(max_length=256, verbose_name='Address')),
                ('iframe', models.TextField(blank=True, null=True, verbose_name='iFrame HTML')),
                ('orient', models.CharField(max_length=256, verbose_name='Orient')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('type', models.CharField(choices=[('Premium', 'Premium'), ('Basic', 'Basic')], default='Basic', max_length=7, verbose_name='Type')),
                ('status', models.CharField(blank=True, choices=[('Hit', 'Hit'), ('New', 'New'), ('Sale', 'Sale')], max_length=4, null=True, verbose_name='Status')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/store/products/%Y/%m/%d', verbose_name='Photo')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_uz', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('no_in_stock', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number in stock')),
                ('purchase_count', models.PositiveIntegerField(default=0, verbose_name='Purchase count')),
                ('is_constructable', models.BooleanField(default=False, verbose_name='Constructable status')),
                ('active', models.BooleanField(default=True, verbose_name='Is active')),
                ('building_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bm_products', to='store.buildingmaterial', verbose_name='Building material')),
                ('car_brands', models.ManyToManyField(blank=True, related_name='products', to='store.carbrand', verbose_name='Car brands')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.category', verbose_name='Category')),
                ('main_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mc_products', to='store.color', verbose_name='Main color')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Product',
            },
        ),
        migrations.CreateModel(
            name='PremiumPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/store/products/premium_photos/%Y/%m/', verbose_name='Photo')),
                ('ordinal_number', models.PositiveIntegerField(verbose_name='Ordinal number')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
            options={
                'verbose_name': 'Premium photo',
                'verbose_name_plural': 'Premium photos',
                'ordering': ['ordinal_number'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('photo', models.ImageField(upload_to='images/store/products/%Y/%m/%d', verbose_name='Photo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='store.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product photo',
                'verbose_name_plural': 'Product photos',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='store.carbrand', verbose_name='Car brands')),
            ],
            options={
                'verbose_name': 'Car model',
                'verbose_name_plural': 'Car models',
                'unique_together': {('brand', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Articul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articuls', to='store.carmodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articuls', to='store.product')),
            ],
            options={
                'verbose_name': 'Articul',
                'verbose_name_plural': 'Articuls',
            },
        ),
    ]
