# Generated by Django 4.2.1 on 2023-08-11 11:22

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=128, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=128, null=True, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=128, null=True, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
            },
        ),
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Car brand',
                'verbose_name_plural': 'Car brands',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('brand', models.ManyToManyField(related_name='cars', to='store.carbrand', verbose_name='Car brands')),
            ],
            options={
                'verbose_name': 'Car model',
                'verbose_name_plural': 'Car models',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('hex_value', models.CharField(max_length=24, verbose_name='Hex value')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='UZ', verbose_name='Phone number')),
                ('is_official', models.BooleanField(default=False, verbose_name='Is official?')),
                ('region', models.CharField(max_length=128, verbose_name='Region')),
                ('district', models.CharField(max_length=128, verbose_name='City or district')),
                ('address', models.CharField(max_length=256, verbose_name='Address')),
                ('orient', models.CharField(max_length=256, verbose_name='Orient')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
            },
        ),
        migrations.CreateModel(
            name='Polik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('type', models.CharField(choices=[('Premium', 'Premium'), ('Basic', 'Basic')], default='Basic', max_length=7, verbose_name='Type')),
                ('status', models.CharField(blank=True, choices=[('Hit', 'Hit'), ('New', 'New'), ('Sale', 'Sale')], max_length=4, null=True, verbose_name='Status')),
                ('photo', models.ImageField(upload_to='images/store/products/%Y/%m/%d', verbose_name='Photo')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_ru', models.TextField(null=True, verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('description_uz', models.TextField(null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=24, verbose_name='Price')),
                ('purchase_count', models.PositiveIntegerField(default=0, verbose_name='Purchase count')),
                ('is_constructed', models.BooleanField(default=False, verbose_name='Is constructed?')),
                ('active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('building_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bm_%(class)ss', to='store.buildingmaterial', verbose_name='Building material')),
                ('car_brands', models.ManyToManyField(related_name='%(class)ss', to='store.carbrand', verbose_name='Car brands')),
                ('car_models', models.ManyToManyField(related_name='%(class)ss', to='store.carmodel', verbose_name='Car models')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='store.category', verbose_name='Category')),
                ('main_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='store.color', verbose_name='Main color')),
            ],
            options={
                'verbose_name': 'Polik',
                'verbose_name_plural': 'Poliks',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('object_id', models.PositiveIntegerField(verbose_name='Object id')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('photo', models.ImageField(upload_to='images/store/products/%Y/%m/%d', verbose_name='Photo')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('carcover', 'polik', 'nakidka')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Product photo',
                'verbose_name_plural': 'Product photos',
            },
        ),
        migrations.CreateModel(
            name='Nakidka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('type', models.CharField(choices=[('Premium', 'Premium'), ('Basic', 'Basic')], default='Basic', max_length=7, verbose_name='Type')),
                ('status', models.CharField(blank=True, choices=[('Hit', 'Hit'), ('New', 'New'), ('Sale', 'Sale')], max_length=4, null=True, verbose_name='Status')),
                ('photo', models.ImageField(upload_to='images/store/products/%Y/%m/%d', verbose_name='Photo')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_ru', models.TextField(null=True, verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('description_uz', models.TextField(null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=24, verbose_name='Price')),
                ('purchase_count', models.PositiveIntegerField(default=0, verbose_name='Purchase count')),
                ('is_constructed', models.BooleanField(default=False, verbose_name='Is constructed?')),
                ('active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('building_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bm_%(class)ss', to='store.buildingmaterial', verbose_name='Building material')),
                ('car_brands', models.ManyToManyField(related_name='%(class)ss', to='store.carbrand', verbose_name='Car brands')),
                ('car_models', models.ManyToManyField(related_name='%(class)ss', to='store.carmodel', verbose_name='Car models')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='store.category', verbose_name='Category')),
                ('main_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='store.color', verbose_name='Main color')),
            ],
            options={
                'verbose_name': 'Nakidka',
                'verbose_name_plural': 'Nakidkas',
            },
        ),
        migrations.CreateModel(
            name='CarCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('type', models.CharField(choices=[('Premium', 'Premium'), ('Basic', 'Basic')], default='Basic', max_length=7, verbose_name='Type')),
                ('status', models.CharField(blank=True, choices=[('Hit', 'Hit'), ('New', 'New'), ('Sale', 'Sale')], max_length=4, null=True, verbose_name='Status')),
                ('photo', models.ImageField(upload_to='images/store/products/%Y/%m/%d', verbose_name='Photo')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_ru', models.TextField(null=True, verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('description_uz', models.TextField(null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=24, verbose_name='Price')),
                ('purchase_count', models.PositiveIntegerField(default=0, verbose_name='Purchase count')),
                ('is_constructed', models.BooleanField(default=False, verbose_name='Is constructed?')),
                ('active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('has_kant', models.BooleanField(default=True, verbose_name='Has Kant?')),
                ('building_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bm_%(class)ss', to='store.buildingmaterial', verbose_name='Building material')),
                ('car_brands', models.ManyToManyField(related_name='%(class)ss', to='store.carbrand', verbose_name='Car brands')),
                ('car_models', models.ManyToManyField(related_name='%(class)ss', to='store.carmodel', verbose_name='Car models')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='store.category', verbose_name='Category')),
                ('central_part_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cp_%(class)ss', to='store.color', verbose_name='Central part color')),
                ('central_part_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cp_%(class)ss', to='store.buildingmaterial', verbose_name='Central material')),
                ('kant_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='k_%(class)ss', to='store.color', verbose_name='Kant color')),
                ('main_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='store.color', verbose_name='Main color')),
                ('rear_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rc_%(class)ss', to='store.color', verbose_name='Rear color')),
                ('rear_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rc_%(class)ss', to='store.buildingmaterial', verbose_name='Rear material')),
                ('side_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='s_%(class)ss', to='store.color', verbose_name='Side color')),
                ('side_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='s_%(class)ss', to='store.buildingmaterial', verbose_name='Side material')),
                ('stitch_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='st_%(class)ss', to='store.color', verbose_name='Stitch color')),
            ],
            options={
                'verbose_name': 'Car cover',
                'verbose_name_plural': 'Car covers',
            },
        ),
    ]
