# Generated by Django 4.2.1 on 2023-08-14 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('type', models.CharField(choices=[('Premium', 'Premium'), ('Basic', 'Basic')], default='Basic', max_length=7, verbose_name='Type')),
                ('status', models.CharField(blank=True, choices=[('Hit', 'Hit'), ('New', 'New'), ('Sale', 'Sale')], max_length=4, null=True, verbose_name='Status')),
                ('photo', models.ImageField(upload_to='images/store/products/%Y/%m/%d', verbose_name='Photo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('no_in_stock', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number in stock')),
                ('purchase_count', models.PositiveIntegerField(default=0, verbose_name='Purchase count')),
                ('is_constructed', models.BooleanField(default=False, verbose_name='Is constructed?')),
                ('has_kant', models.BooleanField(default=False, verbose_name='Has Kant?')),
                ('active', models.BooleanField(default=True, verbose_name='Is active')),
                ('building_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bm_products', to='store.buildingmaterial', verbose_name='Building material')),
                ('car_brands', models.ManyToManyField(blank=True, related_name='products', to='store.carbrand', verbose_name='Car brands')),
                ('car_models', models.ManyToManyField(related_name='products', to='store.carmodel', verbose_name='Car models')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.category', verbose_name='Category')),
                ('central_part_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cp_products', to='store.color', verbose_name='Central part color')),
                ('central_part_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cp_products', to='store.buildingmaterial', verbose_name='Central material')),
                ('kant_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='k_products', to='store.color', verbose_name='Kant color')),
                ('main_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mc_products', to='store.color', verbose_name='Main color')),
                ('rear_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rc_products', to='store.color', verbose_name='Rear color')),
                ('rear_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rm_products', to='store.buildingmaterial', verbose_name='Rear material')),
                ('side_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sc_products', to='store.color', verbose_name='Side color')),
                ('side_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sm_products', to='store.buildingmaterial', verbose_name='Side material')),
                ('stitch_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='st_products', to='store.color', verbose_name='Stitch color')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Product',
            },
        ),
        migrations.RemoveField(
            model_name='nakidka',
            name='building_material',
        ),
        migrations.RemoveField(
            model_name='nakidka',
            name='car_brands',
        ),
        migrations.RemoveField(
            model_name='nakidka',
            name='car_models',
        ),
        migrations.RemoveField(
            model_name='nakidka',
            name='category',
        ),
        migrations.RemoveField(
            model_name='nakidka',
            name='main_color',
        ),
        migrations.RemoveField(
            model_name='polik',
            name='building_material',
        ),
        migrations.RemoveField(
            model_name='polik',
            name='car_brands',
        ),
        migrations.RemoveField(
            model_name='polik',
            name='car_models',
        ),
        migrations.RemoveField(
            model_name='polik',
            name='category',
        ),
        migrations.RemoveField(
            model_name='polik',
            name='main_color',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='object_id',
        ),
        migrations.DeleteModel(
            name='CarCover',
        ),
        migrations.DeleteModel(
            name='Nakidka',
        ),
        migrations.DeleteModel(
            name='Polik',
        ),
        migrations.AddField(
            model_name='photo',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='store.product', verbose_name='Product'),
            preserve_default=False,
        ),
    ]
