# Generated by Django 4.2.1 on 2023-07-24 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cartitem_product'),
        ('orders', '0004_remove_orderitem_product_orderitem_content_type_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0002_remove_user_liked_products_alter_usertoken_created_and_more'),
        ('store', '0002_rename_description_de_product_description_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
            },
        ),
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Car brand',
                'verbose_name_plural': 'Car brands',
            },
        ),
        migrations.CreateModel(
            name='CarCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('type', models.CharField(choices=[('p', 'Premium'), ('b', 'Basic')], default='b', max_length=1, verbose_name='Type')),
                ('status', models.CharField(choices=[('h', 'Hit'), ('n', 'New'), ('s', 'Sale')], default='n', max_length=1, verbose_name='Status')),
                ('photo', models.ImageField(upload_to='images/store/products/%(class)ss/%Y/%m/%d', verbose_name='Photo')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_ru', models.TextField(null=True, verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('description_uz', models.TextField(null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=24, verbose_name='Price')),
                ('purchase_count', models.PositiveIntegerField(default=0, verbose_name='Purchase count')),
                ('is_constructed', models.BooleanField(default=False, verbose_name='Is constructed?')),
                ('active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('has_kant', models.BooleanField(default=True, verbose_name='Has Kant?')),
                ('building_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bm_%(class)ss', to='store.buildingmaterial', verbose_name='Building material')),
                ('car_brands', models.ManyToManyField(related_name='%(class)ss', to='store.carbrand', verbose_name='Car brands')),
            ],
            options={
                'verbose_name': 'Car cover',
                'verbose_name_plural': 'Car covers',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('brand', models.ManyToManyField(related_name='cars', to='store.carbrand', verbose_name='Car brands')),
            ],
            options={
                'verbose_name': 'Car model',
                'verbose_name_plural': 'Car models',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Nakidka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('type', models.CharField(choices=[('p', 'Premium'), ('b', 'Basic')], default='b', max_length=1, verbose_name='Type')),
                ('status', models.CharField(choices=[('h', 'Hit'), ('n', 'New'), ('s', 'Sale')], default='n', max_length=1, verbose_name='Status')),
                ('photo', models.ImageField(upload_to='images/store/products/%(class)ss/%Y/%m/%d', verbose_name='Photo')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_ru', models.TextField(null=True, verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('description_uz', models.TextField(null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=24, verbose_name='Price')),
                ('purchase_count', models.PositiveIntegerField(default=0, verbose_name='Purchase count')),
                ('is_constructed', models.BooleanField(default=False, verbose_name='Is constructed?')),
                ('active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('building_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bm_%(class)ss', to='store.buildingmaterial', verbose_name='Building material')),
                ('car_brands', models.ManyToManyField(related_name='%(class)ss', to='store.carbrand', verbose_name='Car brands')),
                ('car_models', models.ManyToManyField(related_name='%(class)ss', to='store.carmodel', verbose_name='Car models')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='store.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Nakidka',
                'verbose_name_plural': 'Nakidkas',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('object_id', models.PositiveIntegerField(verbose_name='Object id')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('photo', models.ImageField(upload_to='images/store/products/%Y/%m/%d', verbose_name='Photo')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('carcover', 'polik', 'nakidka')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Product photo',
                'verbose_name_plural': 'Product photos',
            },
        ),
        migrations.CreateModel(
            name='Polik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=256, null=True, verbose_name='Title')),
                ('type', models.CharField(choices=[('p', 'Premium'), ('b', 'Basic')], default='b', max_length=1, verbose_name='Type')),
                ('status', models.CharField(choices=[('h', 'Hit'), ('n', 'New'), ('s', 'Sale')], default='n', max_length=1, verbose_name='Status')),
                ('photo', models.ImageField(upload_to='images/store/products/%(class)ss/%Y/%m/%d', verbose_name='Photo')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_ru', models.TextField(null=True, verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('description_uz', models.TextField(null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=24, verbose_name='Price')),
                ('purchase_count', models.PositiveIntegerField(default=0, verbose_name='Purchase count')),
                ('is_constructed', models.BooleanField(default=False, verbose_name='Is constructed?')),
                ('active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('building_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bm_%(class)ss', to='store.buildingmaterial', verbose_name='Building material')),
                ('car_brands', models.ManyToManyField(related_name='%(class)ss', to='store.carbrand', verbose_name='Car brands')),
                ('car_models', models.ManyToManyField(related_name='%(class)ss', to='store.carmodel', verbose_name='Car models')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='store.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Polik',
                'verbose_name_plural': 'Poliks',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufacturing_method',
        ),
        migrations.RemoveField(
            model_name='product',
            name='picture_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='style',
        ),
        migrations.RemoveField(
            model_name='product',
            name='target_room',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='product',
        ),
        migrations.RemoveField(
            model_name='video',
            name='product',
        ),
        migrations.RemoveField(
            model_name='color',
            name='hexa_value',
        ),
        migrations.AddField(
            model_name='color',
            name='hex_value',
            field=models.CharField(default=0, max_length=24, verbose_name='Hex value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='is_official',
            field=models.BooleanField(default=False, verbose_name='Is official?'),
        ),
        migrations.AlterField(
            model_name='store',
            name='orient',
            field=models.CharField(default=0, max_length=256, verbose_name='Orient'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='ManufacturingMethod',
        ),
        migrations.DeleteModel(
            name='PictureType',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.DeleteModel(
            name='Style',
        ),
        migrations.DeleteModel(
            name='TargetRoom',
        ),
        migrations.DeleteModel(
            name='Variant',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AddField(
            model_name='polik',
            name='main_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='store.color', verbose_name='Main color'),
        ),
        migrations.AddField(
            model_name='nakidka',
            name='main_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='store.color', verbose_name='Main color'),
        ),
        migrations.AddField(
            model_name='carcover',
            name='car_models',
            field=models.ManyToManyField(related_name='%(class)ss', to='store.carmodel', verbose_name='Car models'),
        ),
        migrations.AddField(
            model_name='carcover',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='store.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='carcover',
            name='central_part_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cp_%(class)ss', to='store.color', verbose_name='Central part color'),
        ),
        migrations.AddField(
            model_name='carcover',
            name='central_part_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cp_%(class)ss', to='store.buildingmaterial', verbose_name='Central material'),
        ),
        migrations.AddField(
            model_name='carcover',
            name='kant_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='k_%(class)ss', to='store.color', verbose_name='Kant color'),
        ),
        migrations.AddField(
            model_name='carcover',
            name='main_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='store.color', verbose_name='Main color'),
        ),
        migrations.AddField(
            model_name='carcover',
            name='rear_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rc_%(class)ss', to='store.color', verbose_name='Rear color'),
        ),
        migrations.AddField(
            model_name='carcover',
            name='rear_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rc_%(class)ss', to='store.buildingmaterial', verbose_name='Rear material'),
        ),
        migrations.AddField(
            model_name='carcover',
            name='side_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='s_%(class)ss', to='store.color', verbose_name='Side color'),
        ),
        migrations.AddField(
            model_name='carcover',
            name='side_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='s_%(class)ss', to='store.buildingmaterial', verbose_name='Side material'),
        ),
        migrations.AddField(
            model_name='carcover',
            name='stitch_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='st_%(class)ss', to='store.color', verbose_name='Stitch color'),
        ),
    ]
