# Generated by Django 4.2.1 on 2023-08-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='car_brands',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='store.carbrand', verbose_name='Car brands'),
        ),
    ]
