# Generated by Django 4.2.1 on 2023-08-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_car_brands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='car_brands',
            field=models.ManyToManyField(blank=True, related_name='products', to='store.carbrand', verbose_name='Car brands'),
        ),
    ]
