# Generated by Django 4.2.1 on 2023-08-23 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_car_brands'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='central_part_color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='central_part_material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='has_kant',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_constructed',
        ),
        migrations.RemoveField(
            model_name='product',
            name='kant_color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rear_color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rear_material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='side_color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='side_material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stitch_color',
        ),
    ]
