# Generated by Django 4.2.1 on 2023-08-24 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_central_part_color_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together={('brand', 'title')},
        ),
    ]
