# Generated by Django 4.2.1 on 2023-08-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_carmodel_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='is_official',
            field=models.BooleanField(default=True, verbose_name='Is official?'),
        ),
    ]
