# Generated by Django 4.2.1 on 2023-09-12 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/store/products/premium_photos/%Y/%m/', verbose_name='Photo')),
                ('ordinal_number', models.PositiveIntegerField(verbose_name='Ordinal number')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
            options={
                'verbose_name': 'Premium photo',
                'verbose_name_plural': 'Premium photos',
                'ordering': ['ordinal_number'],
            },
        ),
    ]
