# Generated by Django 4.2.1 on 2023-09-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_premiumphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_constructable',
            field=models.BooleanField(default=False, verbose_name='Constructable status'),
        ),
    ]
