# Generated by Django 4.2.1 on 2023-09-20 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_articul'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='car_models',
        ),
    ]
