# Generated by Django 4.2.1 on 2023-09-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_product_car_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='iframe',
            field=models.TextField(blank=True, null=True, verbose_name='iFrame HTML'),
        ),
    ]
