# Generated by Django 4.2.1 on 2023-09-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_store_iframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/store/products/%Y/%m/%d', verbose_name='Photo'),
        ),
    ]
