# Generated by Django 4.2.1 on 2023-07-24 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_buildingmaterial_carbrand_carcover_carmodel_category_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('cart', '0003_remove_cartitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='car_model',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='store.carmodel', verbose_name='Car model'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='content_type',
            field=models.ForeignKey(default=0, limit_choices_to={'model__in': ('carcover', 'polik', 'nakidka')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='object_id',
            field=models.PositiveIntegerField(default=0, verbose_name='Object id'),
            preserve_default=False,
        ),
    ]
