# Generated by Django 4.2.1 on 2023-09-20 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_product_car_models'),
        ('cart', '0004_alter_cartitem_car_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='articul',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.articul'),
            preserve_default=False,
        ),
    ]
