# Generated by Django 4.2.1 on 2023-08-14 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_remove_nakidka_building_material_and_more'),
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='object_id',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='on_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='store.product', verbose_name='On product'),
        ),
    ]
