# Generated by Django 4.2.1 on 2023-09-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0003_inquiry_is_one_click'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryCall',
            fields=[
            ],
            options={
                'verbose_name': 'Inquiry for call',
                'verbose_name_plural': 'Inquiries for call',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inquiries.inquiry',),
        ),
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name': 'Inquiry on product', 'verbose_name_plural': 'Inquiries on product'},
        ),
        migrations.AddField(
            model_name='inquiry',
            name='is_call',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='is_product',
            field=models.BooleanField(default=True),
        ),
    ]
