# Generated by Django 4.2.1 on 2023-08-18 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='district_en',
        ),
        migrations.RemoveField(
            model_name='address',
            name='region_en',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street_en',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='text_en',
        ),
    ]
