# Generated by Django 4.2.1 on 2023-08-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_carmodel_unique_together'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_products',
            field=models.ManyToManyField(blank=True, related_name='liked_users', to='store.product'),
        ),
        migrations.DeleteModel(
            name='UserProductLikeManager',
        ),
    ]
