# Generated by Django 4.2.1 on 2023-08-24 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_liked_products_delete_userproductlikemanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='liked_products',
        ),
    ]
