# Generated by Django 4.1.5 on 2023-01-18 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
        ('webinar', '0002_alter_comment_options_alter_webinar_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('course', 'Course'), ('video_lesson', 'Video Lesson'), ('webinar', 'Webinar')], max_length=63, verbose_name='Type')),
                ('payment_type', models.CharField(choices=[('one_time', 'One Time'), ('two_time', 'Two Time'), ('four_time', 'Four Time')], max_length=63, verbose_name='Payment Type')),
                ('provider', models.CharField(choices=[('payme', 'Payme'), ('click', 'Click'), ('karmon_pay', 'Karmon Pay'), ('uzum_bank', 'Uzum Bank'), ('card', 'Card')], max_length=63, verbose_name='Provider')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='course.course', verbose_name='Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('video_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='course.videolesson', verbose_name='Video lesson')),
                ('webinar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='webinar.webinar', verbose_name='Webinar')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.CharField(max_length=255, verbose_name='Transaction ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('paid', 'Paid'), ('failed', 'Failed')], max_length=63, verbose_name='Status')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid At')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.order', verbose_name='Order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
