# Generated by Django 4.2.1 on 2023-08-30 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0005_remove_order_payment_method_order_is_canceled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMerchantRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('header', models.TextField(verbose_name='Header')),
                ('body', models.TextField(verbose_name='Body')),
                ('method', models.CharField(max_length=32, verbose_name='Method')),
                ('response', models.TextField(blank=True, null=True)),
                ('response_status_code', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Payment Merchant Request Log',
                'verbose_name_plural': 'Payment Merchant Request Logs',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('transaction_id', models.CharField(max_length=255, null=True, verbose_name='Transaction ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('paid', 'Paid'), ('failed', 'Failed'), ('canceled', 'Canceled')], max_length=63, verbose_name='Status')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid At')),
                ('cancel_time', models.DateTimeField(blank=True, null=True, verbose_name='Cancel Time')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='InstallmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('detail', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('failed', 'Failed'), ('success', 'Success')], max_length=63, verbose_name='Status')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Order')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.transaction', verbose_name='Transaction')),
            ],
            options={
                'verbose_name': 'Installment Log',
                'verbose_name_plural': 'Installment Logs',
            },
        ),
    ]
