# Generated by Django 4.1.5 on 2023-01-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(max_length=255, null=True, verbose_name='Transaction ID'),
        ),
    ]
