# Generated by Django 4.1.5 on 2023-02-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cancel_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancel Time'),
        ),
    ]
