# Generated by Django 4.1.5 on 2023-02-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_order_is_canceled'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMerchantRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('payme', 'Payme'), ('click', 'Click'), ('karmon_pay', 'Karmon Pay'), ('uzum_bank', 'Uzum Bank'), ('card', 'Card')], max_length=63, verbose_name='Provider')),
                ('header', models.TextField(verbose_name='Header')),
                ('body', models.TextField(verbose_name='Body')),
                ('method', models.CharField(max_length=32, verbose_name='Method')),
                ('response', models.TextField(blank=True, null=True)),
                ('response_status_code', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
