# Generated by Django 4.1.5 on 2023-02-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_usercard'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='token',
            field=models.CharField(max_length=255, null=True, verbose_name='Token'),
        ),
    ]
