# Generated by Django 4.1.5 on 2023-02-15 18:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0009_usercard_confirmed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercard',
            options={'verbose_name': 'User Card', 'verbose_name_plural': 'User Cards'},
        ),
        migrations.AlterUniqueTogether(
            name='usercard',
            unique_together={('user', 'card_number')},
        ),
    ]
