# Generated by Django 4.1.5 on 2023-02-16 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_alter_usercard_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='payment.usercard', verbose_name='User card'),
        ),
    ]
