# Generated by Django 4.1.5 on 2023-02-16 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_order_user_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('failed', 'Failed'), ('success', 'Success')], max_length=63, verbose_name='Status')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.order', verbose_name='Order')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.transaction', verbose_name='Transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
